title: Rubin Hood
description: Minimalistischer Jekyll-Blog
baseurl: "/rubinhood-blog"
url: ""
theme: null
exclude: [Gemfile, Gemfile.lock, node_modules, vendor]

markdown: kramdown

kramdown:
input: GFM
hard_wrap: false

highlighter: rouge


permalink: /:year/:month/:day/:title/
